### ISSUE TITLE
FIX: READMEの修正

### ISSUE THREAD

**Issue by nyacos** [nyacos/love_pdca#36]
下記の通り、READMEを修正したいと考えているのですが、修正してもよろしいでしょうか。

# 背景
MVPリリースの期限(12/19)が迫っているため、
MVPに含める内容のうち一部をその他の機能（本リリース）に加えたいです。
高度な機能（https://esa-pages.io/p/sharing/2315/posts/21347/58e9cb9424e9ce60c9fb.html ）として記載のある「LINE通知」をMVP時点で実装しているため、機能面では問題ないと判断しています。
また、主な変更点となるチャット機能はこのアプリのコアな機能（恋愛を進める上でのタスク管理をする、恋愛相談をして管理人から回答をもらう）からは外れるためMVPリリースではなく本リリースに加えたいと考えています。

※元々卒業試験で使用していたリポジトリで開発を進めていましたが、デプロイがうまく行かず、アプリを作成しなおしたため、新しいリポジトリとなっております。 卒業試験時のやりとり等確認されたい場合は、下記URLよりご確認いただけますと幸いです。 https://github.com/nyacos/lovepdca

# README 変更前
https://github.com/nyacos/love_pdca?tab=readme-ov-file#%E5%AE%9F%E8%A3%85%E3%82%92%E4%BA%88%E5%AE%9A%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B%E6%A9%9F%E8%83%BD
## MVP
ユーザー登録（LINE）
LINEログイン
PLAN一覧
DO一覧
CHECK一覧
ACTION（ユーザー交流用コミュニティ）一覧
ACTION登録
ACTION詳細
LINE通知 
・自分が作成した相談にコメントが付いた場合に通知 
・自分がコメントした相談にさらにコメントが付いた場合に通知 
・別のユーザーからチャットが送られてきた際に通知
チャット 
・特定の相手に相談したり、相談したことのその後について報告したりすることで、ユーザー同士の繋がりを濃くします。
管理人から相談に対する回答が必ず得られる 
・管理人である私、にゃこすから相談に対する回答を必ず得られるようにします。経験に基づきアドバイスをして、相談したけど回答が得られない、回答は他のユーザーから得られたけど解決に至らないといったケースを防ぎます。

## その他の機能
PLAN登録
PLAN編集
PLAN削除
DO登録
DO編集
DO削除
ACTION編集
ACTION削除
レコメンド 
・相談した人に対して過去の似たような解決済みの相談をレコメンドしたり、相談に対して回答をした人に対して、似たような未解決の相談（得意分野の相談）をレコメンドする。

# README 変更後
変更箇所を**太字**にします
## MVP
ユーザー登録（LINE）
LINEログイン
PLAN一覧
DO一覧
CHECK一覧
ACTION（ユーザー交流用コミュニティ）一覧
ACTION登録
ACTION詳細
**ACTION編集
ACTION削除
ACTIONへのコメント登録**
**LINE通知 
・その日に投稿されたACTIONを一定時刻（毎日21時）に通知**
管理人から相談に対する回答が必ず得られる 
・管理人である私、にゃこすから相談に対する回答を必ず得られるようにします。経験に基づきアドバイスをして、相談したけど回答が得られない、回答は他のユーザーから得られたけど解決に至らないといったケースを防ぎます。

## その他の機能
PLAN登録
PLAN編集
PLAN削除
DO登録
DO編集
DO削除
**ACTIONへのコメント編集
ACTIONへのコメント削除
LINE通知 
・別のユーザーからチャットが送られてきた際に通知
・自分が作成した相談にコメントが付いた場合に通知 
・自分がコメントした相談にさらにコメントが付いた場合に通知 
チャット 
・特定の相手に相談したり、相談したことのその後について報告したりすることで、ユーザー同士の繋がりを濃くします。**
レコメンド 
・相談した人に対して過去の似たような解決済みの相談をレコメンドしたり、相談に対して回答をした人に対して、似たような未解決の相談（得意分野の相談）をレコメンドする。

**Comment by kenchasonakai** [comment]
LGTMです！

高度な機能としてLINE通知が入っているので大丈夫です
実装頑張ってください

**Comment by nyacos** [comment]
ご確認いただきありがとうございます！
